server:
  port: 8888
  servlet:
    context-path: /news
spring:
  application:
    name: cloud-new-column-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.121.58.171:3306/news?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 754217510lj
  redis:
    host: 118.121.58.171
    port: 6379
    password: 754217510lj
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml